FROM docker.io/ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en

# Install PHP 8.3 and required extensions
RUN apt-get update && apt-get install -y \
    software-properties-common curl && \
    add-apt-repository ppa:ondrej/php && \
    apt-get update && apt-get install -y \
    php8.3 \
    php8.3-xml \
    php8.3-mbstring \
    php8.3-curl \
    php8.3-cli \
    composer \
    git \
    openssh-client

RUN curl -L https://github.com/pantheon-systems/terminus/releases/download/3.6.1/terminus.phar \
        --output /usr/local/bin/terminus \
    && chmod +x /usr/local/bin/terminus \
    && /usr/local/bin/terminus self:update